version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: video_processing
      POSTGRES_USER: video_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    environment:
      - DATABASE_URL=postgresql://video_user:your_password@db/video_processing
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    environment:
      - DATABASE_URL=postgresql://video_user:your_password@db/video_processing
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data: